"""IHN Atlas — the IHN heat network: the district main, the proposed
connection and the plant room under the block, with the dispatch model a click
away.

One app, two views — the same shape as ``app_srv_atlas.py`` and
``app_kld_atlas.py``, so the site atlases behave identically:

* default — the atlas (``ihn_atlas.html``): a still, daytime three.js
  satellite scene of the district with the network drawn on it and the 76 × 25 m plant
  room cut away, eight camera views with a caption that follows the view, a
  key, layers, and a pulsing BLOX badge over the plant room with a standing
  "Heat Network 3D" call to action.
* ``?view=3d`` — the dispatch model: Heat Network 3D (``heat_network_3d.html``,
  the same file the investor pack serves, with all of its data), full-bleed,
  with an "Atlas" control to come back.

The model is a separate route rather than an in-page overlay, so the atlas
page carries none of the model's weight and the model gets the whole browser
window. ``heat_network_3d.html`` is shared with the investor apps and must stay
untouched: the atlas chrome for it (the back control) lives in
``ihn_heat_chrome.html`` and is appended at serve time. The atlas page is
generated by ``build_ihn_atlas.py`` in the IHN client's contract folder.

Self-contained: everything is inlined, no database and no secrets.

Public tool. Run locally:  streamlit run app_ihn_atlas.py
"""
from pathlib import Path

import streamlit as st

VIEW_3D = st.query_params.get("view") == "3d"

st.set_page_config(
    page_title="IHN Atlas — Heat Network 3D" if VIEW_3D else "IHN Atlas",
    page_icon=":material/device_thermostat:",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# Both views are the whole page: strip Streamlit's chrome and padding so the
# iframe owns the full viewport (each page lays out its own bar, panels and
# controls inside it).
st.markdown(
    """
    <style>
      [data-testid="stHeader"], [data-testid="stToolbar"],
      [data-testid="stDecoration"], [data-testid="stStatusWidget"],
      [data-testid="stBottomBlockContainer"], footer {display:none !important;}
      [data-testid="stAppViewContainer"] {overflow:hidden !important;}
      /* stMain scrolls by default and reserves a scrollbar gutter, which would
         leave a dead strip down the right-hand edge of a full-bleed scene */
      [data-testid="stMain"] {overflow:hidden !important; height:100dvh !important;}
      [data-testid="stMain"] .block-container,
      [data-testid="stMainBlockContainer"], .block-container {
          padding:0 !important; margin:0 !important; max-width:100% !important;}
      [data-testid="stVerticalBlock"], [data-testid="stVerticalBlockBorderWrapper"] {
          gap:0 !important;}
      [data-testid="stElementContainer"], [data-testid="element-container"] {
          width:100% !important;}
      [data-testid="stIFrame"] {
          height:100dvh !important; width:100% !important; display:block; border:0;}
      html, body, .stApp {overflow:hidden !important; background:#0d1b23 !important;}
    </style>
    """,
    unsafe_allow_html=True,
)

HERE = Path(__file__).resolve().parent

# Read fresh from the main script each run (Streamlit re-runs this script but
# can keep imported modules cached, so reading here keeps the embedded pages
# current after every redeploy).
if VIEW_3D:
    html = (HERE / "heat_network_3d.html").read_text(encoding="utf-8")
    chrome = HERE / "ihn_heat_chrome.html"
    if chrome.exists():
        html = html.replace("</body>", chrome.read_text(encoding="utf-8") + "\n</body>", 1)
else:
    html = (HERE / "ihn_atlas.html").read_text(encoding="utf-8")

st.iframe(html, height=900)
